name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test Library
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Unit tests
      run: dotnet test
    - name: Build
      run: dotnet build -c Release
    - name: Documentation
      run: |
        dotnet tool update -g docfx
        docfx docs/docfx.json
    - name: Upload Package
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: src/bin/release/*.nupkg
# creating another zip is not needed because 'package.zip' should exist from previous step
#    - name: Create Zip for Release
#      run: compress-archive -Path src\bin\release\*.nupkg -Destination package.zip
    - name: Get version
      id: vars
      run: |
        $env:ver = Get-Content src\bin\release\ver.txt
        echo version=$env:ver >> $env:GITHUB_OUTPUT
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}      
    - name: Create release
      if: ${{ github.event_name == 'push' }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Creating release"
        echo gh release create --generate-notes v${{ steps.vars.outputs.version }} package.zip
        gh release create -t ${{ steps.vars.outputs.version }} --generate-notes v${{ steps.vars.outputs.version }} package.zip#package
